// Copy for the staff app (/staff). Internal and English only, so it's outside the translated
// content (and the translators' spreadsheet).
export const staffCopy = {
  appName: "CHS Staff",
  seoTitle: "CHS Staff",
  signIn: {
    title: "Sign in",
    intro: "For CHS staff. Use the email you have in Fergus.",
    email: "Email",
    password: "Password",
    submit: "Sign in",
    wrong: "That email and password don't match.",
    tooMany: "Too many attempts. Wait 15 minutes and try again.",
    failed: "Couldn't sign in. Check your signal and try again.",
    demo: "Mock mode: any email, password “demo”.",
  },
  signOut: "Sign out",
  diary: {
    today: "Today",
    tomorrow: "Tomorrow",
    yesterday: "Yesterday",
    previous: "Previous day",
    next: "Next day",
    empty: "Nothing in your diary for this day.",
    allDay: "All day",
    onHold: "On hold",
    failed: "Couldn't load your diary. Pull down or tap to retry.",
    retry: "Retry",
    hello: (name: string) => `Morning, ${name}`,
    find: "Job number",
    findButton: "Open",
    notFound: "No job with that number.",
  },
  job: {
    back: "Diary",
    jobNo: (no: string) => `Job ${no}`,
    customer: "Customer",
    contact: "Contact",
    call: "Call",
    email: "Email",
    site: "Site",
    directions: "Directions",
    description: "Job details",
    phases: "Work",
    complete: "Mark work complete",
    completeConfirm:
      "Mark this work complete? The office will invoice it, and the customer sees “Work complete”.",
    completed: "Work complete",
    hold: "Put on hold",
    holdReason: "Why? (for the office)",
    holdConfirm: "Put on hold",
    resume: "Resume job",
    onHold: "This job is on hold",
    notes: "Notes",
    notePlaceholder: "What did you find or do?",
    addNote: "Add note",
    photos: "Photos",
    takePhoto: "Take or add photos",
    uploading: (done: number, total: number) =>
      `Uploading ${done} of ${total}…`,
    share: "Share with customer",
    shareHelp: "Shows on “Track my repair”.",
    shared: "Shared",
    internal: "Internal",
    noNotes: "No notes yet.",
    noPhotos: "No photos yet.",
    saved: "Saved",
    failed: "Couldn't save. Check your signal and try again.",
    cancel: "Cancel",
    previousPhoto: "Previous photo",
    nextPhoto: "Next photo",
  },
}
